name: Run f.js Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-fjs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Ensure package.json with ESM configuration exists
        run: |
          if [ ! -f package.json ]; then
            echo '{ "type": "module" }' > package.json
          else
            # If package.json exists but does not contain "type": "module", append it.
            grep -q '"type": "module"' package.json || sed -i '1s/^/{\n  "type": "module",\n/' package.json
          fi

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm install @solana/web3.js axios node-fetch chalk bs58 tweetnacl https-proxy-agent socks-proxy-agent node-telegram-bot-api

      - name: Run f.js script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_IDS: ${{ secrets.ADMIN_IDS }}
        run: node f.js
